server:
  tomcat:
    accesslog:
      enabled: false
    max-threads: 800
    min-spare-threads: 10
    uri-encoding: UTF-8

logging:
  level:
    org.springframework: ERROR
    org.apache.catalina: ERROR
    com.yql.framework: DEBUG

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.0.2:3306/zhanglin_bd2?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&useNewIO=true&autoReconnectForPools=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 50
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testOnBorrow: true
      testWhileIdle: true
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
      hibernate:
        ddl-auto: update
        naming:
          strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      properties:
        hibernate:
           dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
xiaoyu:
  auth-urls: /role/*,/menu/*,/log/*,/icon/*,/dept/*
mybatis:
  configuration:
    autoMappingBehavior: FULL
    mapUnderscoreToCamelCase: true
